/*
 * Auto-generated by .githooks/pre-commit — do NOT edit by hand.
 * `version` is the running commit count (ticks by one each commit); `hash` is
 * the commit this build sits on top of; `date` is when it was stamped.
 * Loaded as a plain global, same as config.js. See README "Version stamp".
 */
self.BUILD_INFO = { version: 21, hash: "d328c1b", date: "2026-07-01" };
